<a href="https://colab.research.google.com/github/Anaju7/Aulas_Python/blob/main/Aula08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Conceitos basicos <br>
Criação e manipulação com numpy

In [ ]:
import numpy as np


# criação de arrays
# a partir de uma lista

lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


#### Sequencias

In [ ]:
# gera *arange* numeros aleatorios
seqArray = np.arange(10)
print(seqArray)

[0 1 2 3 4 5 6 7 8 9]


#### Manipulações de array

redimensionamento:

In [ ]:
meuArr = np.array([1, 2, 3, 4, 5, 6])
matriz = meuArr.reshape(2, 3)
print(matriz)

[[1 2 3]
 [4 5 6]]


Acesso a elementos:

In [ ]:
print(matriz[1][2])

6


operações matematicas basicas

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)
print(a * b)

[5 7 9]
[ 4 10 18]


##QUESTÕES

In [ ]:
array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
arr = np.arange(16).reshape(4, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
a = np.array([2,4,6,8,10])
b = a**2
print(b)


[  4  16  36  64 100]


In [ ]:
arr = np.arange(3)

matrizA = np.array([arr, arr, arr])
matrizb = np.array([arr, arr, arr])
print(matrizA + matrizb)


[[0 2 4]
 [0 2 4]
 [0 2 4]]
