<a href="https://colab.research.google.com/github/Anaju7/Aulas_Python/blob/main/Aula09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aula 09 - 14/10/2024

## Estatistica e medias

In [ ]:
import numpy as np

Medias:

In [ ]:
arr = np.array([1,2,3,4,5])
media = np.mean(arr)
print(media)

3.0


Mediana

In [ ]:
arr = np.array([1,2,3,4,5])
mediana = np.median(arr)
print(mediana)

3.0


Medias de dispersão

* Desvio Padrão <br>
Variancia

In [ ]:
std_value = np.std(arr)
print(std_value)

# Variancia
# distribuição dos dados
var = np.var(arr)
print(var)

1.4142135623730951
2.0


Medidas de Posição

* Percentis

Percentis indicam a posição relativa de um valor dentro de um conjunto de dados.

Percentil 25(P25): 25% ddos estão abaixo deste valor.
Percentil 75(P75): 75% dos valores estão abaixo deste valor.

In [ ]:
per_25 = np.percentile(arr, 25)
per_75 = np.percentile(arr, 75)
print(per_25)
print(per_75)

2.0
4.0


Outras Funções Estatísticas

*  Correlação



1. Correlação Positiva: Diretamente proporcional

2. Correlação Negativa: Inversamente proporcional

3. Correlação Nula: Sem relação entre as grande



In [ ]:
arr01 = np.array([1,2,3,4,5])
arr02 = np.array([5,4,3,2,1])
corr = np.corrcoef(arr01, arr02)
print(corr)

[[ 1. -1.]
 [-1.  1.]]


### Exercicios <br>
1) Dado o array scores = np.array([85, 88, 90, 78, 92, 94, 89, 84, 81, 79]), calcule a média, mediana e o desvio padrão.

2) Para o mesmo array scores, determine os valores do 10º e 90º percentis.

3) Calcule a variância de um array com os valores de 1 a 10.

4) Dados os arrays x = np.array([1, 2, 3, 4, 5]) e y = np.array([5, 6, 7, 8, 9]), calcule o coeficiente de correlação entre eles.

In [ ]:
meuArray = np.array([85, 88, 90, 78, 92, 94, 89, 84, 81, 79])
print(f'media: {np.mean(meuArray)}, mediana: {np.median(meuArray)}, desvio padrão: {np.std(meuArray)}')

media: 86.0, mediana: 86.5, desvio padrão: 5.215361924162119


In [ ]:
per_10 = np.percentile(meuArray, 10)
per_90 = np.percentile(meuArray, 90)
print(f'percentil 10: {per_10}')
print(f'percentil 90: {per_90}')

percentil 10: 78.9
percentil 90: 92.2


In [ ]:
arrVar = np.arange(1, 11)
print(np.var(arrVar))

8.25


In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 6, 7, 8, 9])
print(np.corrcoef(x, y))

[[1. 1.]
 [1. 1.]]


## Operações com Matrizes e Vetores

* Produto Interno e Externo

In [ ]:
# produto interno (Produto Escalar)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))
# 1 * 4 + 2 * 5 + 3 * 6 = 4 + 10 + 18 = 32

32


In [ ]:
# produto externo (Produto Vetorial)
cross = np.cross(a, b)
print(cross)


[-3  6 -3]


* Produto de Matrizes

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))


[[19 22]
 [43 50]]


Determinante e Traço
* Determinante

In [ ]:
d = np.linalg.det(A)
print(d)

-2.0000000000000004


* Traço

In [ ]:
#  soma da diagonal
# matriz A 1 + 4
trace = np.trace(A)
print(trace)

5


Sistemas lineares

In [ ]:
equacao = np.array([[2, 3], [1, -1]])
resultado = np.array([5, 2])
solucao = np.linalg.solve(equacao, resultado)
print(solucao)


[2.2 0.2]


### Exercicios <br>
1) Dado os vetores u = np.array([1, 3, 5]) e v = np.array([5, 2, 1]), calcule o produto interno e externo.

2) Para a matriz M = np.array([[2, 3, 4], [1, 5, 6], [7, 8, 9]]), determine o determinante e o traço.

3) Resolva o sistema de equações: 3x - y = 1 e 2x + 4y = 6.



In [ ]:
u = np.array([1, 3, 5])
v = np.array([5, 2, 1])
print(f'Produto interno (Produto Escalar): {np.dot(u, v)}')
print(f'Produto externo (Produto Vetorial): {np.cross(u, v)}')

Produto interno (Produto Escalar): 16
Produto externo (Produto Vetorial): [ -7  24 -13]


In [35]:
m = np.array([[2, 3, 4], [1, 5, 6], [7, 8, 9]])
print(f'Determinante: {np.linalg.det(m)}')
print(f'Traço: {np.trace(m)}')

Determinante: -15.000000000000007
Traço: 16


In [36]:
eq = np.array([[3, -1], [2, 4]])
res = np.array([1, 6])
print(np.linalg.solve(eq, res))

[0.71428571 1.14285714]


## Médias: Geométrica, Harmônica

Média Geométrica

In [37]:
from scipy.stats import gmean

In [38]:
data  = np.array([1, 2, 3, 4, 5])
media_geometrica = gmean(data)
print(media_geometrica)

2.6051710846973517


Media Harmonica

In [39]:
from scipy.stats import hmean
Data = np.array([1, 2, 3, 4, 5])
media_harmonica = hmean(data)
print(media_harmonica)

2.18978102189781


### Exercicios <br>
1) Calcule a média aritmética, geométrica e harmônica dos valores [3, 9, 27].

2) Dado um conjunto de notas escolares [85, 90, 78, 92, 88], calcule a média aritmética.

3) Para um conjunto de taxas de crescimento [1.05, 1.1, 1.15], calcule a média geométrica.

In [43]:
arr = np.array([3, 9, 27])
print(np.mean(arr))
print(gmean(arr))
print(hmean(arr))

13.0
9.000000000000002
6.230769230769231


In [44]:
grade = np.array([85, 90, 78, 92, 88])
print(np.mean(grade))

86.6


In [45]:
taxa = np.array([1.05, 1.1, 1.15])
print(gmean(taxa))

1.0992419018963262
